language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - npm run lint
  - npm run test:ci
  - npm run stryker:ci
  - npm run build:compiled
  - npm run build:bundle
  - npm run build:doc
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
