name: Build and test
run-name: ${{ github.actor }} is building and testing
on: workflow_call

jobs:
  install:
    uses: ./.github/workflows/install.yml

  install-website:
    uses: ./.github/workflows/install-website.yml

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Restore dependencies from cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
      - name: Lint
        run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Restore dependencies from cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
      - name: Cache build
        uses: actions/cache@v4
        id: build
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ hashFiles('src/**') }}
      - name: Compile
        if: steps.build.outputs.cache-hit != 'true'
        run: yarn build:compiled
      - name: Bundle
        if: steps.build.outputs.cache-hit != 'true'
        run: yarn build:bundle

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Restore dependencies from cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
      - name: Cache unit tests
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ runner.os }}-unit-tests-${{ hashFiles('src/**') }}
      - name: Unit tests
        run: yarn test:ci

  build-documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    needs: install-website

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Restore dependencies from cache
        uses: actions/cache@v4
        with:
          path: website/node_modules
          key: ${{ runner.os }}-website-node_modules-${{ hashFiles('website/yarn.lock') }}
      - name: Cache documentation
        uses: actions/cache@v4
        id: dist_docs
        with:
          path: dist/docs
          key: ${{ runner.os }}-documentation-${{ hashFiles('src/**') }}-${{ hashFiles('website/*,website/src/**,website/static/**') }}
          fail-on-cache-miss: true
      - name: Build documentation
        if: steps.dist_docs.outputs.cache-hit != 'true'
        run: cd website && yarn build

  report-coverage:
    name: Report coverage
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Restore dependencies from cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
      - name: Restore unit tests
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ runner.os }}-unit-tests-${{ hashFiles('src/**') }}
      # - name: Report coverage
      #   run: yarn report-coverage
      - name: Report coverage
        uses: coverallsapp/github-action@v2
